export const GEO_PIN_LOCATION = 'bi bi-geo-alt-fill'
export const CLOCK_FILL = 'bi bi-clock-fill'
export const QUOTE = 'bi bi-quote'
export const PHONE_FILL = 'bi bi-telephone-fill'
export const ENVELOPE_FILL = 'bi bi-envelope-fill'
